import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import { Suspense } from "react";
import Footer from "./components/Header/footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Suspense fallback={<header className="bg-white shadow" />}>
        <Header />
      </Suspense>
      <div>
        {children}
      </div>
      <Footer />
      </body>
    </html>
  );
}
